/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE fev-contactsBaseService PLEASE EDIT ../fev-contacts.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { FevContacts } from '../../domain/drishti_db/fev-contacts';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../FevContacts.service.ts
 */

/*
 * SCHEMA DB FevContacts
 *
	{
		NUMBER: {
			type: 'String'
		},
		name: {
			type: 'String'
		},
		phone: {
			type: 'String'
		},
		photo: {
			type: 'String'
		},
		relation: {
			type: 'String'
		},
		userid: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		uid: {
			type: Schema.ObjectId,
			ref : "FevContacts"
		},
	}
 *
 */
@Injectable()
export class FevContactsBaseService {

    private fevcontactsCollection: AngularFirestoreCollection<FevContacts>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.fevcontactsCollection = afs.collection<FevContacts>('fevcontacts');
    }


    // CRUD METHODS

    /**
    * FevContactsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: FevContacts): Promise<DocumentReference> {
        return this.fevcontactsCollection.add(item);
    }

    /**
    * FevContactsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.fevcontactsCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * FevContactsService.findByuid
    *   @description CRUD ACTION findByuid
    *   @param Objectid key Id of model to search for
    *
    */
    findByUid(id: string): Observable<any[]> {
        return this.afs.collection('fevcontacts', ref => ref.where('uid', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as FevContacts;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * FevContactsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<FevContacts> {
        return this.afs.doc<FevContacts>('fevcontacts/' + id);
    }

    /**
    * FevContactsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<FevContacts[]> {
        return this.afs.collection('fevcontacts').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as FevContacts;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * FevContactsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<FevContacts>, item: FevContacts): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
